In [ ]:
import numpy as np

#prezzi del titolo e del bond oggi
S0 = 10
B0 = 10

#incertezza del payoff del titolo e del bond domani
S1 = np.array((20, 5))
B1 = np.array((11, 11))

#vettore dei prezzi
M0 = np.array((S0, B0))
M0

array([10, 10])

In [ ]:
#matrice dei payoff
M1 = np.array((S1, B1)).T
M1

array([[20, 11],
       [ 5, 11]])

In [ ]:
#funzione Bernoulli Utility di avversione al rischio
def u(x):
  return np.sqrt(x)

#due protafogli con pesi diversi
phi_A = np.array((0.75, 0.25))
phi_D = np.array((0.25, 0.75))

np.dot(M0, phi_A) == np.dot(M0, phi_D)

True

In [ ]:
#payoff incerto di un portafoglio
A1 = np.dot(M1, phi_A)
A1

array([17.75,  6.5 ])

In [ ]:
#payoff incerto dell'altro portafoglio
D1 = np.dot(M1, phi_D)
D1

array([13.25,  9.5 ])

In [17]:
#la misura di probabilità
P = np.array((0.5, 0.5))

#funzione utilità attesa
def EUT(x):
  return np.dot(P, u(x))

#i valori di utilità per i due payoffs incerti
EUT(A1), EUT(D1)

(3.381292321692286, 3.3611309730623735)

In [19]:
from scipy.optimize import minimize

#budget dell'agente
w = 10

#vincolo di budget da utilizzare con minimizza
cons = {'type': 'eq', 'fun': lambda phi: np.dot(M0, phi) - w}

#la funzione di utilità attesa definita sui portafogli
def EUT_(phi):
  x = np.dot(M1, phi) 
  return EUT(x)

opt = minimize(lambda phi: -EUT_(phi),#minimizzando -EUT_(phi) si massimizza EUT_(phi)
               x0 = phi_A,#l'ipotesi iniziale per l'ottimizzazione
               constraints = cons)#il vincolo del budget applicato
#risultati ottimali, includendo il portafoglio ottimale sotto x
opt

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: -3.385015999493397
       x: [ 6.112e-01  3.888e-01]
     nit: 4
     jac: [-1.692e+00 -1.693e+00]
    nfev: 12
    njev: 4

In [20]:
#L'ottimale (la più alta) utilità attesa data dal budget di w = 10
EUT_(opt['x'])

3.385015999493397